// Mock data for MTC Pro CMMS

export const users = [
  { id: '1', email: 'admin@company.com', name: 'John Admin', role: 'admin', password: 'admin123' },
  { id: '2', email: 'manager@company.com', name: 'Sarah Manager', role: 'manager', password: 'manager123' },
  { id: '3', email: 'tech@company.com', name: 'Mike Technician', role: 'technician', password: 'tech123' },
];

export const workOrders = [
  {
    id: 'WO-1001',
    title: 'Air Compressor Maintenance',
    equipment: 'Compressor #3',
    equipmentId: 'EQ-001',
    priority: 'high',
    status: 'open',
    assignedTo: 'Mike Technician',
    createdDate: '2025-12-01',
    dueDate: '2025-12-10',
    description: 'Routine maintenance check and oil change',
    type: 'preventive',
    estimatedHours: 2,
    actualHours: 0,
  },
  {
    id: 'WO-1002',
    title: 'HVAC System Repair',
    equipment: 'HVAC Unit A',
    equipmentId: 'EQ-002',
    priority: 'critical',
    status: 'in-progress',
    assignedTo: 'Mike Technician',
    createdDate: '2025-11-28',
    dueDate: '2025-12-05',
    description: 'Fan motor replacement and filter cleaning',
    type: 'corrective',
    estimatedHours: 4,
    actualHours: 2.5,
  },
  {
    id: 'WO-1003',
    title: 'Conveyor Belt Inspection',
    equipment: 'Conveyor #5',
    equipmentId: 'EQ-003',
    priority: 'medium',
    status: 'completed',
    assignedTo: 'Mike Technician',
    createdDate: '2025-11-25',
    dueDate: '2025-11-30',
    completedDate: '2025-11-29',
    description: 'Monthly inspection and alignment check',
    type: 'preventive',
    estimatedHours: 1.5,
    actualHours: 1,
  },
  {
    id: 'WO-1004',
    title: 'Forklift Battery Check',
    equipment: 'Forklift #12',
    equipmentId: 'EQ-004',
    priority: 'low',
    status: 'scheduled',
    assignedTo: 'Mike Technician',
    createdDate: '2025-12-03',
    dueDate: '2025-12-15',
    description: 'Battery water level check and terminal cleaning',
    type: 'preventive',
    estimatedHours: 0.5,
    actualHours: 0,
  },
];

export const equipment = [
  {
    id: 'EQ-001',
    name: 'Compressor #3',
    category: 'Air Systems',
    manufacturer: 'Atlas Copco',
    model: 'GA-37',
    serialNumber: 'AC-2021-1234',
    location: 'Building A - Floor 2',
    status: 'operational',
    installDate: '2021-03-15',
    lastService: '2025-11-15',
    nextService: '2025-12-15',
    criticality: 'high',
    image: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=400',
  },
  {
    id: 'EQ-002',
    name: 'HVAC Unit A',
    category: 'Climate Control',
    manufacturer: 'Carrier',
    model: 'AquaEdge 19DV',
    serialNumber: 'CA-2020-5678',
    location: 'Building A - Roof',
    status: 'maintenance-required',
    installDate: '2020-06-20',
    lastService: '2025-10-01',
    nextService: '2025-12-01',
    criticality: 'critical',
    image: 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=400',
  },
  {
    id: 'EQ-003',
    name: 'Conveyor #5',
    category: 'Material Handling',
    manufacturer: 'Siemens',
    model: 'CB-500',
    serialNumber: 'SI-2019-9012',
    location: 'Warehouse - Section C',
    status: 'operational',
    installDate: '2019-08-10',
    lastService: '2025-11-29',
    nextService: '2025-12-29',
    criticality: 'medium',
    image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=400',
  },
  {
    id: 'EQ-004',
    name: 'Forklift #12',
    category: 'Vehicles',
    manufacturer: 'Toyota',
    model: '8FBCU25',
    serialNumber: 'TY-2022-3456',
    location: 'Warehouse - Bay 3',
    status: 'operational',
    installDate: '2022-01-05',
    lastService: '2025-11-20',
    nextService: '2025-12-20',
    criticality: 'medium',
    image: 'https://images.unsplash.com/photo-1565003179661-c7c4b2e12e7d?w=400',
  },
];

export const preventiveMaintenance = [
  {
    id: 'PM-001',
    name: 'Monthly Air Compressor Service',
    equipmentId: 'EQ-001',
    equipment: 'Compressor #3',
    frequency: 'monthly',
    lastCompleted: '2025-11-15',
    nextDue: '2025-12-15',
    status: 'scheduled',
    tasks: ['Check oil level', 'Inspect filters', 'Check pressure settings', 'Listen for unusual sounds'],
  },
  {
    id: 'PM-002',
    name: 'Quarterly HVAC Maintenance',
    equipmentId: 'EQ-002',
    equipment: 'HVAC Unit A',
    frequency: 'quarterly',
    lastCompleted: '2025-09-01',
    nextDue: '2025-12-01',
    status: 'overdue',
    tasks: ['Replace filters', 'Check refrigerant levels', 'Inspect electrical connections', 'Clean condenser coils'],
  },
  {
    id: 'PM-003',
    name: 'Weekly Conveyor Inspection',
    equipmentId: 'EQ-003',
    equipment: 'Conveyor #5',
    frequency: 'weekly',
    lastCompleted: '2025-11-29',
    nextDue: '2025-12-06',
    status: 'scheduled',
    tasks: ['Check belt tension', 'Lubricate bearings', 'Inspect rollers', 'Test emergency stop'],
  },
];

export const inventory = [
  {
    id: 'PART-001',
    partNumber: 'FLT-2500',
    name: 'Air Filter - Standard',
    category: 'Filters',
    quantity: 24,
    reorderLevel: 10,
    reorderQuantity: 20,
    unitCost: 15.99,
    location: 'Warehouse A - Shelf 12',
    supplier: 'Industrial Supply Co',
    status: 'in-stock',
  },
  {
    id: 'PART-002',
    partNumber: 'OIL-5W30',
    name: 'Compressor Oil 5W-30',
    category: 'Lubricants',
    quantity: 8,
    reorderLevel: 5,
    reorderQuantity: 12,
    unitCost: 45.50,
    location: 'Warehouse A - Shelf 5',
    supplier: 'Atlas Copco',
    status: 'low-stock',
  },
  {
    id: 'PART-003',
    partNumber: 'BELT-450',
    name: 'Conveyor Belt 450mm',
    category: 'Belts',
    quantity: 2,
    reorderLevel: 3,
    reorderQuantity: 5,
    unitCost: 285.00,
    location: 'Warehouse B - Section 3',
    supplier: 'Siemens Parts',
    status: 'critical',
  },
  {
    id: 'PART-004',
    partNumber: 'BATT-12V',
    name: 'Forklift Battery 12V',
    category: 'Batteries',
    quantity: 15,
    reorderLevel: 8,
    reorderQuantity: 10,
    unitCost: 120.00,
    location: 'Warehouse A - Battery Room',
    supplier: 'Toyota Parts',
    status: 'in-stock',
  },
];

export const vendors = [
  {
    id: 'VEN-001',
    name: 'Industrial Supply Co',
    contact: 'Robert Smith',
    email: 'robert@industrialsupply.com',
    phone: '(555) 123-4567',
    address: '123 Industrial Blvd, City, ST 12345',
    category: 'General Parts',
    rating: 4.5,
    status: 'active',
  },
  {
    id: 'VEN-002',
    name: 'Atlas Copco',
    contact: 'Jennifer Lee',
    email: 'j.lee@atlascopco.com',
    phone: '(555) 234-5678',
    address: '456 Compressor Way, City, ST 12346',
    category: 'OEM Parts',
    rating: 5.0,
    status: 'active',
  },
  {
    id: 'VEN-003',
    name: 'Siemens Parts',
    contact: 'Michael Johnson',
    email: 'support@siemens.com',
    phone: '(555) 345-6789',
    address: '789 Technology Dr, City, ST 12347',
    category: 'OEM Parts',
    rating: 4.8,
    status: 'active',
  },
];

export const purchaseOrders = [
  {
    id: 'PO-2501',
    vendor: 'Industrial Supply Co',
    vendorId: 'VEN-001',
    orderDate: '2025-12-01',
    expectedDate: '2025-12-08',
    status: 'pending',
    total: 1245.80,
    items: [
      { partId: 'PART-001', partName: 'Air Filter - Standard', quantity: 40, unitCost: 15.99 },
      { partId: 'PART-002', partName: 'Compressor Oil 5W-30', quantity: 12, unitCost: 45.50 },
    ],
  },
  {
    id: 'PO-2502',
    vendor: 'Siemens Parts',
    vendorId: 'VEN-003',
    orderDate: '2025-11-28',
    expectedDate: '2025-12-05',
    receivedDate: '2025-12-04',
    status: 'received',
    total: 1425.00,
    items: [
      { partId: 'PART-003', partName: 'Conveyor Belt 450mm', quantity: 5, unitCost: 285.00 },
    ],
  },
];

export const dashboardStats = {
  openWorkOrders: 15,
  overdueWorkOrders: 3,
  scheduledPM: 8,
  criticalEquipment: 2,
  lowStockItems: 5,
  monthlyWorkOrders: 47,
  avgCompletionTime: 3.2,
  equipmentUptime: 96.5,
};
